# Updated .github/workflows/embedmd.yml
name: Dataset Structure Documentation
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-structure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create directory structure
        run: |
          mkdir -p AnimalHaze3k/{train/{train_hazy,train_clean},test/{test_clean,test_hazy},val/{val_clean,val_hazy}}
          
      - name: Generate structure file
        run: |
          tree -d --noreport --noleaf AnimalHaze3k > structure.txt
          
      - name: Commit structure
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Update dataset structure"
          file_pattern: |
            structure.txt
