name: Update Documentation
on:
  push:
    paths: [structure.txt]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - run: go install github.com/campoy/embedmd@latest
      - run: embedmd -w README.md
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Update structure reference"
